name: rxGuardian
description: "Pharmacy Management System"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  highlight: ^0.7.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  fluttertoast: ^8.2.12
  get: ^4.7.2
  shared_preferences: ^2.5.3
  json_annotation: ^4.8.1
  intl: ^0.20.2

dev_dependencies:
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
