// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9E8tIVbdG8qm1m4HyBISjEufmfxqcV8',
    appId: '1:169848521079:web:fd75c99f75f3bdeba66172',
    messagingSenderId: '169848521079',
    projectId: 'fir-dbd23',
    authDomain: 'fir-dbd23.firebaseapp.com',
    storageBucket: 'fir-dbd23.firebasestorage.app',
    measurementId: 'G-B7HLZBPDKB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3f3wK0NMLn8PiH6Uea5en0SB7muyHbzw',
    appId: '1:169848521079:ios:eb5416107f2f2f86a66172',
    messagingSenderId: '169848521079',
    projectId: 'fir-dbd23',
    storageBucket: 'fir-dbd23.firebasestorage.app',
    iosBundleId: 'com.codemint.codeMintFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp9E8tIVbdG8qm1m4HyBISjEufmfxqcV8',
    appId: '1:169848521079:web:cbeb1b82b0444407a66172',
    messagingSenderId: '169848521079',
    projectId: 'fir-dbd23',
    authDomain: 'fir-dbd23.firebaseapp.com',
    storageBucket: 'fir-dbd23.firebasestorage.app',
    measurementId: 'G-G6P3PMZTGC',
  );
}
